"""
Django settings for hiren project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
import sentry_sdk
from kombu import Exchange, Queue
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

from utils.cors_generator import generate_cors_regex_from_hosts
from utils.ip import get_local_ip
from utils.env import require_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("secret_key")
if not SECRET_KEY:
    raise ImproperlyConfigured("The 'secret_key' environment variable must be set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("debug", "False").lower() == "true"

allowed_hosts_value = os.environ.get("allowed_hosts", "")
if allowed_hosts_value:
    ALLOWED_HOSTS = [
        host.strip() for host in allowed_hosts_value.split(",") if host.strip()
    ]
else:
    ALLOWED_HOSTS = []


# Production security hardening (no-ops in DEBUG so local dev over http keeps working).
# HTTPS required for remote; HTTP allowed only behind this
# explicit LAN/dev opt-in, never implicitly via DEBUG alone.
AMBULO_ALLOW_HTTP = os.environ.get("ambulo_allow_http", "false").lower() == "true"

if not DEBUG and not AMBULO_ALLOW_HTTP:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("secure_hsts_seconds", 60 * 60 * 24 * 365))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "django_celery_results",
    "drf_spectacular",
    "accounts",
    "sync",
    "tracking",
    "health",
    "imports",
    "social",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "utils.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# SHOW_TOOLBAR_CALLBACK below always renders the toolbar, which breaks the
# Django test client (no browser to render HTML into) — never load it under
# pytest, regardless of DEBUG.
RUNNING_TESTS = "pytest" in sys.modules

if DEBUG and not RUNNING_TESTS:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.insert(1, "debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "hiren.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hiren.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "NAME": require_env("db_name"),
        "ENGINE": "django.db.backends.postgresql",
        "USER": require_env("db_user"),
        "PASSWORD": require_env("db_password"),
        "HOST": require_env("db_host"),
        "PORT": os.environ.get("db_port", "5432"),
        # "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "pool": True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("time_zone", "UTC")
TRUSTED_PROXY_IPS = tuple(
    ip.strip()
    for ip in os.environ.get("trusted_proxy_ips", "127.0.0.1,::1").split(",")
    if ip.strip()
)

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Import uploads / export archives
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# debug toolbar
if DEBUG:
    INTERNAL_IPS = list(set(get_local_ip()))
    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# logger
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {"()": "django.utils.log.RequireDebugFalse"},
        "require_debug_true": {"()": "django.utils.log.RequireDebugTrue"},
        "request_id": {"()": "utils.logging.RequestIDFilter"},
    },
    "formatters": {
        "main_formatter": {
            "format": "%(levelname)s:%(name)s: %(message)s "
            "[request_id=%(request_id)s] (%(asctime)s; %(filename)s:%(lineno)d)",
            "datefmt": "%d-%m-%Y %H:%M:%S",
        },
        "json_formatter": {
            "()": "utils.logging.JSONFormatter",
        },
    },
    "handlers": {
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false", "request_id"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "console": {
            "level": "DEBUG",
            "filters": ["require_debug_true", "request_id"],
            "class": "logging.StreamHandler",
            "formatter": "main_formatter",
        },
        "production_file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/main.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 7,
            "formatter": "json_formatter",
            "filters": ["require_debug_false", "request_id"],
        },
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/main_debug.log",
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 7,
            "formatter": "main_formatter",
            "filters": ["require_debug_true", "request_id"],
        },
        "null": {
            "class": "logging.NullHandler",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["mail_admins", "console"],
            "level": "ERROR",
            "propagate": True,
        },
        "django": {
            "handlers": [
                "null",
            ],
        },
        "py.warnings": {
            "handlers": [
                "null",
            ],
        },
        "": {
            "handlers": ["console", "production_file", "debug_file"],
            "level": "DEBUG",
        },
        # 'django.db.backends': {
        #      'handlers': ['console'],
        #      'level': 'DEBUG',
        # },
    },
}

# date for to support 'deshi' aka normal style
DATE_INPUT_FORMATS = ["%d-%m-%Y"]
DATE_FORMAT = "d-m-Y"

# DRF
DEFAULT_RENDERER_CLASSES = ("rest_framework.renderers.JSONRenderer",) + (
    ("rest_framework.renderers.BrowsableAPIRenderer",) if DEBUG else ()
)

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "utils.filters.SchemaDjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/minute",
        "user": "150/minute",
        "provider-webhook": "120/minute",
        "login": "10/minute",
    },
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
    "DEFAULT_RENDERER_CLASSES": DEFAULT_RENDERER_CLASSES,
    "DEFAULT_PAGINATION_CLASS": "utils.pagination.AmbuloPageNumberPagination",
    "PAGE_SIZE": 20,
    "COERCE_DECIMAL_TO_STRING": False,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "utils.permissions.MustChangePasswordPermission",
    ],
    "EXCEPTION_HANDLER": "utils.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Ambulo API",
    "DESCRIPTION": "Self-hostable OwnTracks + Google Fit style location/fitness API.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# sentry for error tracking
if not DEBUG:
    sentry_sdk.init(
        dsn=os.environ.get("sentry_dsn"),
        # This is a product with user location - request bodies routinely contain location, secret location from your
        # side chick, so never send PII to Sentry.
        send_default_pii=False,
        traces_sample_rate=float(os.environ.get("sentry_traces_sample_rate", "0.0")),
        integrations=[DjangoIntegration(), CeleryIntegration()],
    )

# cors
CORS_ALLOWED_ORIGIN_REGEXES = generate_cors_regex_from_hosts(ALLOWED_HOSTS)

if DEBUG:
    CORS_ORIGIN_ALLOW_ALL = True


# Enable/disable self-service registration on POST /api/accounts/users/register/.
# Defaults to open in DEBUG and closed in prod. The first account can always
# register and becomes staff/superuser, even when this is false. Once an
# account exists, this setting controls all further self-service registration.
REGISTRATION_OPEN = (
    os.environ.get("registration_open", "true" if DEBUG else "false").lower() == "true"
)

# JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("jwt_access_minutes", 60))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("jwt_refresh_days", 30))
    ),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Celery
if DEBUG:
    CELERY_BROKER_URL = os.environ.get(
        "rabbitmq_url", "amqp://guest:guest@localhost:5672//"
    )
else:
    CELERY_BROKER_URL = require_env("rabbitmq_url")
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"

# Serialisation
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_DEFAULT_QUEUE = "ambulo.default"
CELERY_TASK_DEFAULT_EXCHANGE = "ambulo"
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = "direct"
CELERY_TASK_DEFAULT_ROUTING_KEY = "ambulo.default"
CELERY_TASK_DEFAULT_DELIVERY_MODE = "persistent"
CELERY_TASK_CREATE_MISSING_QUEUES = False
CELERY_TASK_QUEUES = (
    Queue(
        CELERY_TASK_DEFAULT_QUEUE,
        Exchange(
            CELERY_TASK_DEFAULT_EXCHANGE,
            type=CELERY_TASK_DEFAULT_EXCHANGE_TYPE,
            durable=True,
        ),
        routing_key=CELERY_TASK_DEFAULT_ROUTING_KEY,
        durable=True,
    ),
)

# Reliability
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True  # ack only after task succeeds
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # re-queue if worker dies mid-task
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # fair dispatch — one task at a time per worker
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000  # recycle workers to prevent memory leaks
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False  # avoid deprecated transient pidbox queues
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = True

# Results TTL
CELERY_RESULT_EXPIRES = timedelta(days=15)

# Timezone (inherit from Django)
CELERY_TIMEZONE = os.environ.get("time_zone", "UTC")
CELERY_ENABLE_UTC = True

CELERY_BEAT_SCHEDULE = {
    "recompute-recent-daily-rollups": {
        "task": "health.recompute_recent_rollups",
        "schedule": crontab(hour=2, minute=30),
    },
    "location-retention-cleanup": {
        "task": "tracking.retention_cleanup",
        "schedule": crontab(hour=3, minute=0),
    },
}
