# Generated by Django 6.0.7 on 2026-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("preview_ready", "Preview Ready"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="source_format",
            field=models.CharField(
                choices=[
                    ("ambulo_json", "Ambulo JSON"),
                    ("gpx", "GPX"),
                    ("geojson", "GeoJSON"),
                    ("owntracks", "OwnTracks (.rec/JSON)"),
                    ("owntracks_csv", "OwnTracks CSV"),
                    ("google_takeout", "Google Takeout (locations.json)"),
                    (
                        "google_takeout_semantic",
                        "Google Takeout (Semantic Location History)",
                    ),
                    ("google_fit", "Google Fit (steps CSV)"),
                    ("tcx", "TCX (Google Fit/Garmin workout export)"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("preview_ready", "Preview Ready"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
