# Generated by Django 6.0.7 on 2026-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imports",
            "0002_alter_exportjob_status_alter_importjob_source_format_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="source_format",
            field=models.CharField(
                choices=[
                    ("ambulo_json", "Ambulo JSON"),
                    ("gpx", "GPX"),
                    ("geojson", "GeoJSON"),
                    ("owntracks", "OwnTracks (.rec/JSON)"),
                    ("owntracks_csv", "OwnTracks CSV"),
                    ("google_takeout", "Google Takeout (locations.json)"),
                    (
                        "google_takeout_semantic",
                        "Google Takeout (Semantic Location History)",
                    ),
                    ("tcx", "TCX (Google Fit/Garmin workout export)"),
                ],
                max_length=32,
            ),
        ),
    ]
