# Generated by Django 6.0.7 on 2026-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_location_retention_days_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="e2e_encryption_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Groundwork flag only (SPEC §16, future). No client currently encrypts payloads before upload, and the server does nothing different when this is set — flipping it today has no effect.",
            ),
        ),
    ]
