# Generated by Django 6.0.7 on 2026-07-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_e2e_encryption_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="e2e_encryption_enabled",
            field=models.BooleanField(
                default=False,
                help_text="encrypts payloads before upload, and the server does nothing",
            ),
        ),
    ]
