# Generated by Django 6.0.7 on 2026-07-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_e2e_encryption_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biological_sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
