# Generated by Django 6.0.7 on 2026-07-15 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who blocked this relationship. Only this user may revoke a blocked friendship — otherwise the blocked party could delete the row and immediately re-request (issue.md H3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
