# Generated by Django 6.0.7 on 2026-07-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_friendship_blocked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("friend_accept", "Friend Accepted"),
                    ("friend_geofence", "Friend Geofence Event"),
                ],
                max_length=32,
            ),
        ),
    ]
