# Generated by Django 6.0.7 on 2026-07-15 13:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("horizontal_accuracy", models.FloatField(blank=True, null=True)),
                ("vertical_accuracy", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField()),
                (
                    "battery_level",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "connectivity",
                    models.CharField(
                        choices=[
                            ("wifi", "WiFi"),
                            ("cellular", "Cellular"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "monitoring_mode",
                    models.CharField(
                        choices=[
                            ("quit", "Quit"),
                            ("manual", "Manual"),
                            ("significant", "Significant"),
                            ("move", "Move"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "recorded_at"],
                        name="tracking_lo_user_id_114c48_idx",
                    )
                ],
            },
        ),
    ]
