# Generated by Django 6.0.7 on 2026-07-15 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("work", "Work"),
                            ("gym", "Gym"),
                            ("travel", "Travel"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("radius_meters", models.FloatField(default=100)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("currently_inside", models.BooleanField(default=False)),
                ("last_entered_at", models.DateTimeField(blank=True, null=True)),
                ("last_exited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("distance_meters", models.FloatField(default=0)),
                ("point_count", models.PositiveIntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "end_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_ended",
                        to="tracking.place",
                    ),
                ),
                (
                    "start_place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_started",
                        to="tracking.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["user", "category"], name="tracking_pl_user_id_b56856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["user", "started_at"], name="tracking_tr_user_id_d6e094_idx"
            ),
        ),
    ]
