# Generated by Django 6.0.7 on 2026-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_place_trip_place_tracking_pl_user_id_b56856_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpoint",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
    ]
