# Generated by Django 6.0.7 on 2026-07-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_locationpoint_encrypted_blob_place_encrypted_blob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="state_as_of",
            field=models.DateTimeField(
                blank=True,
                help_text="recorded_at of the point that last determined currently_inside. Guards against out-of-order/concurrent geofence tasks (batch sync, retries) flipping state using a stale point (issue.md M1).",
                null=True,
            ),
        ),
    ]
