# Generated by Django 6.0.7 on 2026-07-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "imports",
            "0002_alter_exportjob_status_alter_importjob_source_format_and_more",
        ),
        ("tracking", "0004_place_state_as_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpoint",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
    ]
