# Generated by Django 6.0.7 on 2026-07-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_locationpoint_import_job_place_import_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationpoint",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
    ]
