# Generated by Django 6.0.7 on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tracking", "0006_alter_locationpoint_encrypted_blob_and_more")]

    operations = [
        migrations.AddField(
            model_name="place",
            name="notify_friends",
            field=models.BooleanField(
                default=False,
                help_text="Send accepted friends enter/exit notifications for this place.",
            ),
        ),
    ]
