# Generated by Django 6.0.7 on 2026-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_place_notify_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationpoint",
            name="speed_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="locationpoint",
            name="trip_id",
            field=models.UUIDField(
                blank=True,
                help_text="Client-assigned Trip grouping id. No FK: client generates Trip and LocationPoint UUIDs independently and may upload points before their trip in the same batch; a trip can also be deleted without invalidating already-synced points.",
                null=True,
            ),
        ),
    ]
