# Generated by Django 6.0.7 on 2026-07-15 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("still", "Still"),
                            ("walking", "Walking"),
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("vehicle", "Vehicle"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("distance_meters", models.FloatField(blank=True, null=True)),
                ("steps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "started_at"],
                        name="health_acti_user_id_a7642a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyRollup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("date", models.DateField()),
                ("steps", models.PositiveIntegerField(default=0)),
                ("distance_meters", models.FloatField(default=0)),
                ("active_minutes", models.PositiveIntegerField(default=0)),
                ("calories", models.FloatField(default=0)),
                ("floors", models.PositiveIntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"),
                        name="unique_daily_rollup_per_user_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("steps", "Steps"),
                            ("distance", "Distance"),
                            ("active_minutes", "Active Minutes"),
                            ("calories", "Calories"),
                            ("floors", "Floors"),
                            ("weight", "Weight"),
                            ("height", "Height"),
                            ("water", "Water"),
                            ("sleep", "Sleep"),
                            ("mood", "Mood"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_value", models.FloatField()),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="health_goal_user_id_35da75_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("steps", "Steps"),
                            ("distance", "Distance"),
                            ("active_minutes", "Active Minutes"),
                            ("calories", "Calories"),
                            ("floors", "Floors"),
                            ("weight", "Weight"),
                            ("height", "Height"),
                            ("water", "Water"),
                            ("sleep", "Sleep"),
                            ("mood", "Mood"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=32)),
                ("recorded_at", models.DateTimeField()),
                ("note", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "metric_type", "recorded_at"],
                        name="health_heal_user_id_eb285e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("note_date", models.DateField()),
                ("context", models.CharField(blank=True, max_length=32)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "note_date"],
                        name="health_note_user_id_a0b85e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("local_rev", models.PositiveIntegerField(default=0)),
                (
                    "server_rev",
                    models.BigIntegerField(db_index=True, default=0, editable=False),
                ),
                (
                    "sync_state",
                    models.CharField(
                        choices=[
                            ("local_only", "Local Only"),
                            ("pending_upload", "Pending Upload"),
                            ("synced", "Synced"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("deleted_pending_sync", "Deleted Pending Sync"),
                        ],
                        default="synced",
                        max_length=32,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("location", "Location"),
                            ("motion", "Motion"),
                            ("health", "Health"),
                            ("import", "Import"),
                            ("server", "Server"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("still", "Still"),
                            ("walking", "Walking"),
                            ("running", "Running"),
                            ("cycling", "Cycling"),
                            ("vehicle", "Vehicle"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("distance_meters", models.FloatField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_set",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-server_rev",),
                "get_latest_by": "server_rev",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "started_at"],
                        name="health_work_user_id_ebbf2b_idx",
                    )
                ],
            },
        ),
    ]
