# Generated by Django 6.0.7 on 2026-07-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysample",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="dailyrollup",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="healthsample",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork (SPEC §16, future flag). Reserved for an opaque client-encrypted payload the server stores without reading. Unused today — no client encrypts before upload, and no server code branches on this field yet.",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("steps", "Steps"),
                    ("distance", "Distance"),
                    ("active_minutes", "Active Minutes"),
                    ("calories", "Calories"),
                    ("floors", "Floors"),
                    ("weight", "Weight"),
                    ("height", "Height"),
                    ("water", "Water"),
                    ("sleep", "Sleep"),
                    ("mood", "Mood"),
                    ("heart_rate", "Heart Rate"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="healthsample",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("steps", "Steps"),
                    ("distance", "Distance"),
                    ("active_minutes", "Active Minutes"),
                    ("calories", "Calories"),
                    ("floors", "Floors"),
                    ("weight", "Weight"),
                    ("height", "Height"),
                    ("water", "Water"),
                    ("sleep", "Sleep"),
                    ("mood", "Mood"),
                    ("heart_rate", "Heart Rate"),
                    ("custom", "Custom"),
                ],
                max_length=32,
            ),
        ),
    ]
