# Generated by Django 6.0.7 on 2026-07-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_activitysample_encrypted_blob_and_more"),
        (
            "imports",
            "0002_alter_exportjob_status_alter_importjob_source_format_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysample",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="dailyrollup",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="healthsample",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this record was created by an import — lets a user identify/revert one specific import batch (issue.md M3).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_set",
                to="imports.importjob",
            ),
        ),
    ]
