# Generated by Django 6.0.7 on 2026-07-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0003_activitysample_import_job_dailyrollup_import_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitysample",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="dailyrollup",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="healthsample",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="encrypted_blob",
            field=models.TextField(
                blank=True,
                default="",
                help_text="E2E-encryption groundwork. Reserved for an opaque client-encrypted payload the server stores without reading",
            ),
        ),
    ]
